version: '3.8'

services:
  nest-tekton-db:
    image: postgres
    container_name: nest-tekton-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
  nest-tekton-api:
    container_name: nest-tekton-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      - nest-tekton-network
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "yarn && yarn start:dev"
    depends_on:
      - nest-tekton-db
networks:
  nest-tekton-network:
