enum ENVIRONMENT {
  API_VERSION = 'v1',
  DB_HOST = 'DB_HOST',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  API_JWT_SECRET_KEY = 'API_JWT_SECRET_KEY',
  EXPIRES_IN = 'EXPIRES_IN',
}

export default ENVIRONMENT;
